name             'boxed-docker'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures boxed-docker'
long_description 'Installs/Configures boxed-docker'
version          '0.1.0'

depends 'yum-epel'
depends 'docker'
